// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vaiajwmedonyhhbtoxhn.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhaWFqd21lZG9ueWhoYnRveGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzk3MzIsImV4cCI6MjA2MDIxNTczMn0.oae-zUk6YV_AByp-_c3DwMxrMKTFW0LGqK97P2kVywA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);